#!/usr/bin/env python3

import json
import tempfile
import sys

from resource import generate_version_hash


def main():
    data = _get_data()
    versions = []

    if data['version']:
        versions.append(data['version'])

    versions.append({'ref': generate_version_hash()})

    print(json.dumps(versions))


def _get_data():
    json_data = sys.stdin.read()

    with tempfile.NamedTemporaryFile(delete=False, prefix='check-') as f:
        f.write(bytes(json_data, 'utf-8'))

    data = json.loads(json_data)
    return data


if __name__ == '__main__':
    main()
