#!/usr/bin/env python3

import json
import os
import sys
import time

from resource import HTTPResource, generate_version_hash


def main():
    """main function for `in` command """
    http_resource = HTTPResource(os.path.basename(__file__), sys.stdin.read())

    response = http_resource.run(sys.argv[1:])
    _save_response(http_resource.http_response_payload, sys.argv[1])

    version = http_resource.input_data.get('version')
    if not version.get('ref') or version.get('ref') == '':
        version = {"ref": generate_version_hash()}

    response_dict = {
      "version": version,
      "metadata": [
        {"name": "time", "value": str(time.time())},
        {"name": "http_response_code", "value": str(http_resource.http_response_code)},
        {"name": "http_response_payload", "value": '%s [...]' % http_resource.http_response_payload[:100]},
      ]
    }

    print (json.dumps(response_dict))


def _save_response(response_data, file_path):
    """save json content as file """
    file_name = '%s/response.json' % os.path.abspath(file_path)

    fo = open(file_name, "wb")
    fo.write(bytes(response_data, 'utf-8'))
    fo.close()

if __name__ == '__main__':
    main()
