#!/usr/bin/env python3

import hashlib
import json
import os
import sys
import time

from resource import HTTPResource


def main():
    """main function for `in` command """
    response = HTTPResource().run(os.path.basename(__file__), sys.stdin.read(), sys.argv[1:])
    _save_response(response, sys.argv[1])

    response_dict = {
      "version": {"ref": _generate_version_hash()},
      "metadata": [
        { "name": "payload", "value": response[:100] },
      ]
    }

    print (json.dumps(response_dict))


def _save_response(json_data, file_path):
    """save json content as file """
    file_name = '%s/response.json' % os.path.abspath(file_path)

    fo = open(file_name, "wb")
    fo.write(bytes(json_data, 'utf-8'))
    fo.close()


def _generate_version_hash():
    time_str = '%s' % time.time()
    hash_object = hashlib.md5(time_str.encode())
    hash_str = hash_object.hexdigest()

    return hash_str[:6]

if __name__ == '__main__':
    main()
